-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps hereby
-- This file is automatically loaded by lazyvim.config.init
-- vim.keymap.set("n", "<leader>bb", "Nop")
